In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
list=[100, 200, 300, 400]

n=np.array(list)

In [ ]:
list=[100, 200, 300, 400]

list1=[500, 600, 700, 900]

n=np.array([list, list1])

In [ ]:
n

array([[100, 200, 300, 400],
       [500, 600, 700, 900]])

In [ ]:
n.ndim

2

In [ ]:
n.size

8

In [ ]:
n.shape

(2, 4)

In [ ]:
arr=np.array(["l",2,3,5], ndmin=5)

In [ ]:
arr

array([[[[['l', '2', '3', '5']]]]], dtype='<U21')

In [ ]:
arr.ndim

5

In [ ]:
name="info"

d=np.fromiter(name, dtype='U2')
d

array(['i', 'n', 'f', 'o'], dtype='<U2')

In [ ]:
import numpy as np

a= np.array([[1, 2, 3,4], [9,8,7,6], [2,3,4,5]])
print(a)

[[1 2 3 4]
 [9 8 7 6]
 [2 3 4 5]]


In [ ]:
f=np.arange(2,11)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
f=np.arange(start=2,stop=10,step=3)
f

array([2, 5, 8])

In [ ]:
arr = np.array([2, 1, 5, 3, 4, 7, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x = np.array([[1, 2], [3, 4]])
y= np.array([[5, 6], [8, 4]])
np.concatenate((x, y), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 8, 4]])

In [ ]:
import numpy as np

iterable = (x*x for x in range(10))

np.fromiter(iterable, int)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
import numpy as np

iterable =  (x*x for x in range(20))

np.fromiter(iterable, int)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [ ]:
import numpy as np

data = np.arange(1,6)

output=np.average(data)

print(data)

print(output)

[1 2 3 4 5]
3.0


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2  = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])


arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])


arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])


arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 2)

print (newarr)

[array([1, 2, 3]), array([4, 5, 6])]


In [ ]:
import numpy as np

arr= np.array([1, 2, 3, 4, 5, 6])

newarr  = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 2)

print(newarr)

[array([[1, 2],
       [3, 4],
       [5, 6]]), array([[ 7,  8],
       [ 9, 10],
       [11, 12]])]
