<a href="https://colab.research.google.com/github/springboardmentorLive/Reality_AI/blob/ananyarohidasshet/IS_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
list =[100,200,300,400]
n=np.array(list)

In [ ]:
n

array([100, 200, 300, 400])

In [ ]:
list1 = [100,200,300,400]
list2 = [300,500,300,600]
n=np.array([list1, list2])

In [ ]:
n


array([[100, 200, 300, 400],
       [300, 500, 300, 600]])

In [ ]:
n.ndim

2

In [ ]:
n.size

8

In [ ]:
n.shape

(2, 4)

In [ ]:
arr=np.array([1,2,3,5],ndmin=5)

In [ ]:
arr

array([[[[[1, 2, 3, 5]]]]])

In [ ]:
arr.ndim

5

In [ ]:
name="info"
d=np.fromiter(name,dtype='U2')
d

array(['i', 'n', 'f', 'o'], dtype='<U2')

In [ ]:
f=np.arange(2,11)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
f=np.arange(start=2,stop=13,step=3)
f

array([ 2,  5,  8, 11])

In [ ]:
arr = np.array([2,3,4,6,2,4,1,8,9,3])
np.sort(arr)

array([1, 2, 2, 3, 3, 4, 4, 6, 8, 9])

In [ ]:
a=np.array([1,2,3,4]) #1 dim
b=np.array([5,6,7,8])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x = np.array([[1,3], [4,5]])
y = np.array([[5,7], [6,9]])
np.concatenate((x,y),axis=0)

array([[1, 3],
       [4, 5],
       [5, 7],
       [6, 9]])

In [ ]:
x = np.array([[1,3], [4,5]])
y = np.array([[5,7], [6,9]])
np.concatenate((x,y),axis=1)

array([[1, 3, 5, 7],
       [4, 5, 6, 9]])

In [ ]:
import numpy as np
iterable = (x*x for x in range (20))
np.fromiter(iterable,int)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [ ]:
import numpy as np
data = np.arange(1,14)
output=np.average(data)
print(data)
print(output)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13]
7.0
