<a href="https://colab.research.google.com/github/springboardmentorLive/Reality_AI/blob/ananyarohidasshet/IS_Stack.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr  = np.stack((arr1,arr2),axis=0)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr  = np.stack((arr1,arr2),axis=1)
print(arr)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [ ]:
import numpy as np #hstack
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr  = np.hstack((arr1,arr2))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr  = np.vstack((arr1,arr2))
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr  = np.dstack((arr1,arr2))
print(arr)

[[[ 1  6]
  [ 2  7]
  [ 3  8]
  [ 4  9]
  [ 5 10]]]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5])]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
newarr = np.array_split(arr,3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2 3]
[4 5]
[6 7]


In [ ]:
arr = np.array([[ 1 , 6],[ 2 , 7],[ 3 , 8],[ 4 , 9],[ 5 , 10]])
newarr = np.array_split(arr,3)
print(newarr)

[array([[1, 6],
       [2, 7]]), array([[3, 8],
       [4, 9]]), array([[ 5, 10]])]
