In [ ]:
import numpy as np

: 

In [ ]:
list = [100,200,300,400]
n = np.array(list)

In [ ]:
n

array([100, 200, 300, 400])

In [ ]:
list = [100,200,300,400]
list1 = ["Hello","India","34",400]
n = np.array([list,list1])
n

array([['100', '200', '300', '400'],
       ['Hello', 'India', '34', '400']], dtype='<U21')

In [ ]:
n.ndim

2

In [ ]:
n.size

8

In [ ]:
n.shape

(2, 4)

In [ ]:
arr = np.array([1,2,3,4], ndmin = 5)

In [ ]:
arr

array([[[[[1, 2, 3, 4]]]]])

In [ ]:
name = "Rishu"
d = np.fromiter(name, dtype = "U2")
d

array(['R', 'i', 's', 'h', 'u'], dtype='<U2')

In [ ]:
r = np.array([[90,80,70,60],[5,4,3,2],[11,22,33,44]])
print("Array:",r)
print("Shape:", r.shape)
print("Size:", r.size)
print("Dimensions:", r.ndim)

Array: [[90 80 70 60]
 [ 5  4  3  2]
 [11 22 33 44]]
Shape: (3, 4)
Size: 12
Dimensions: 2


In [ ]:
z = np.arange(6,12)
z

array([ 6,  7,  8,  9, 10, 11])

In [ ]:
y = np.arange(6,12,step=2)
y

array([ 6,  8, 10])

In [ ]:
x = np.arange(start = 6, stop = 26, step = 4)
x

array([ 6, 10, 14, 18, 22])

In [ ]:
arr = np.array([5, 3, 8, 1, 7])
sorted = np.sort(arr)
print("Sorted:", sorted)

Sorted: [1 3 5 7 8]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate((a, b))
print(c)


[1 2 3 4 5 6]


In [ ]:
e = np.array([[1, 2],[3, 4]])
f = np.array([[5, 6],[7, 8]])
result = np.concatenate((e, f), axis=0)
print(result)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
arr = np.fromiter((i*i for i in range(6)), int)
arr

array([ 0,  1,  4,  9, 16, 25])

In [ ]:
data = np.arange(1,6)
out = np.average(data)
print(out)

3.0


In [ ]:
#class 2 - 26/11/25

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

h = np.hstack((a, b))
print(h)

[1 2 3 4 5 6]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

v = np.vstack((a, b))
print(v)

[[1 2 3]
 [4 5 6]]


In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

v = np.vstack((A, B))
print(v)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

s = np.stack((a, b), axis=0)
print(s)

[[1 2 3]
 [4 5 6]]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

d = np.dstack((a, b))
print(d)

[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

parts = np.array_split(a, 3)
print(parts)
print(parts[0])

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11])]
[1 2 3 4]


In [ ]:
A = np.array([[1, 2],
              [3, 4],
              [5, 6],
              [7, 8]])

parts = np.array_split(A, 3)
print(parts)
print(parts[0])

[array([[1, 2],
       [3, 4]]), array([[5, 6]]), array([[7, 8]])]
[[1 2]
 [3 4]]
