<a href="https://colab.research.google.com/github/springboardmentorLive/Reality_AI/blob/NITISHA_SHINY/Numpy_f5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
list=[1000,2000,3000,4000]
list1=[250,200,350,400]
n=np.array([list,list1])


In [ ]:
n


array([[1000, 2000, 3000, 4000],
       [ 250,  200,  350,  400]])

In [ ]:
n.ndim

2

In [ ]:
n.size

8

In [ ]:
n.shape

(2, 4)

In [ ]:
arr = np.array(["1", 2, 3, 5]).reshape(1,1,1,1,4)
print(arr, arr.dtype)


[[[[['1' '2' '3' '5']]]]] <U21


In [ ]:
name="Nitishashiny"
d=np.fromiter(name,dtype='U2')
d

array(['N', 'i', 't', 'i', 's', 'h', 'a', 's', 'h', 'i', 'n', 'y'],
      dtype='<U2')

In [ ]:
f=np.arange(2,11)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
f=np.arange(start=2,stop=10,step=2)
f

array([2, 4, 6, 8])

In [ ]:
arr=np.array([2,1,4,5,6,7,8,8])
np.sort(arr)

array([1, 2, 4, 5, 6, 7, 8, 8])

In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.concatenate((a,b))


array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[10,20],[30,50]])

result = np.concatenate((x, y), axis=1)
print(result)

[[ 1  2 10 20]
 [ 3  5 30 50]]


In [ ]:
import numpy as np
iterable=(x*x for x in range(10))
np.fromiter(iterable,dtype=int)
arr

array([2, 1, 4, 5, 6, 7, 8, 8])

In [ ]:
import numpy as np
data=np.arange(1,10)
output=np.average(data)
print(data)
print(output)

[1 2 3 4 5 6 7 8 9]
5.0


In [ ]:
import numpy as np
arr1=np.array([23,45,6,67])
arr2=np.array([90,78,67,55])
arr=np.stack((arr1,arr2),axis=0)
print(arr)

[[23 45  6 67]
 [90 78 67 55]]


In [ ]:
import numpy as np
arr1=np.array([23,45,6,67])
arr2=np.array([90,78,67,55])
arr=np.stack((arr1,arr2),axis=1)
print(arr)

[[23 90]
 [45 78]
 [ 6 67]
 [67 55]]


In [ ]:
import numpy as np
arr1=np.array([23,45,6,67])
arr2=np.array([90,78,67,55])
arr=np.hstack((arr1,arr2))
print(arr)

[23 45  6 67 90 78 67 55]


In [ ]:
import numpy as np
arr1=np.array([23,45,6,67])
arr2=np.array([90,78,67,55])
arr=np.vstack((arr1,arr2))
print(arr)

[[23 45  6 67]
 [90 78 67 55]]


In [ ]:
import numpy as np
arr1=np.array([23,45,6,67])
arr2=np.array([90,78,67,55])
arr=np.dstack((arr1,arr2))
print(arr)

[[[23 90]
  [45 78]
  [ 6 67]
  [67 55]]]


In [ ]:
import numpy as np
arr=np.array([23,45,6,67,6,7])
newarr=np.array_split(arr,2)
print (newarr)

[array([23, 45,  6]), array([67,  6,  7])]


In [ ]:
import numpy as np
arr=np.array([23,45,6,67,6,7])
newarr=np.array_split(arr,3)
print (newarr[0])
print (newarr[1])
print (newarr[2])


[23 45]
[ 6 67]
[6 7]


In [ ]:
import numpy as np
arr=np.array([23,45,6,67,6,7])
newarr=np.array_split(arr,7)
print (newarr)

[array([23]), array([45]), array([6]), array([67]), array([6]), array([7]), array([], dtype=int64)]


In [ ]:
import numpy as np
arr=np.array([23,45,6,67,6,7])
newarr=np.array_split(arr,7)
print (newarr[0])
print (newarr[1])
print (newarr[2])


[23]
[45]
[6]


In [ ]:
arr=np.array([[50,40],[40,67],[89,67],[1,2],[78,56]])
newarr=np.array_split(arr,3)
print(newarr)

[array([[50, 40],
       [40, 67]]), array([[89, 67],
       [ 1,  2]]), array([[78, 56]])]


In [ ]:
arr=np.array([[50,40],[40,67],[89,67],[1,2],[78,56]])
newarr=np.array_split(arr,7)
print(newarr)

[array([[50, 40]]), array([[40, 67]]), array([[89, 67]]), array([[1, 2]]), array([[78, 56]]), array([], shape=(0, 2), dtype=int64), array([], shape=(0, 2), dtype=int64)]
