In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
list = [100, 200, 300, 400]
n = np.array(list)

In [ ]:
n

array([100, 200, 300, 400])

In [ ]:
list1 = [100, 200, 300, 400, 900]
list2 = [500, 600, 700, 800, 400]
n = np.array([list1 , list2])

In [ ]:
n

array([[100, 200, 300, 400, 900],
       [500, 600, 700, 800, 400]])

In [ ]:
n.ndim

2

In [ ]:
n.size

10

In [ ]:
n.shape

(2, 5)

In [ ]:
arr = np.array([1,2,3,5], ndmin = 5)
# ndmin forces the created NumPy array to have at least that many dimensions, even if the input is 1D or 2D.

In [ ]:
arr

array([[[[[1, 2, 3, 5]]]]])

In [ ]:
arr.ndim # ndim method tells about the number of dimension in the array

5

In [ ]:
name = "info"
# fromiter is a NumPy function used to create an array from any iterable (like list, tuple, generator) element-by-element.
d = np.fromiter(name, dtype='U21') # one
d

array(['i', 'n', 'f', 'o'], dtype='<U2')

In [ ]:
f = np.arange(2, 10) # start, stop, step
f

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
f = np.arange(start=2, stop = 10, step = 2)
f

array([2, 4, 6, 8])

In [ ]:
arr = np.array([2,3,4,5,2,5,34,3,23])
np.sort(arr)

array([ 2,  2,  3,  3,  4,  5,  5, 23, 34])

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [8,4]])
np.concatenate((x,y), axis=1) # 0 for row wise and 1 for column wise

array([[1, 2, 5, 6],
       [3, 4, 8, 4]])

In [ ]:
import numpy as np
iterable = (x*x for x in range(10))
np.fromiter(iterable,int)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
import numpy as np
data = np.arange(1,6)
output=np.average(data)
print(data)
print(output)

[1 2 3 4 5]
3.0


In [3]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [4]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=0)

print(arr)

[[1 2 3]
 [4 5 6]]


In [1]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [2]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [17]:
arr = np.array([[1,2], [3,4], [5,6], [7,8], [9,10], [11,12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
